backend:
  name: git-gateway
  branch: main
site_url: https://eleanor-walker-v3.netlify.app/
display_url: https://eleanor-walker-v3.netlify.app/
media_folder: static/img
public_folder: /img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: 'journal'
    label: 'Journal'
    folder: 'content/journal'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'journal' }
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'work' }
